apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: zeaho
  labels:
    app: app
spec:
  type: NodePort
  selector:
    app: laravel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80